version: "3.3"
services: 
    app:
        container_name: app
        restart: always
        env_file: 
            - .env
        build:
            context: .
            args: 
                PORT: ${PORT}
        ports: 
            - 3000:${PORT}
        volumes:
            - ".:/app:rw"
        links:
            - mongo
    mongo:
        container_name: mongo
        restart: always
        image: mongo
        ports:
            - 27017:27017
