# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: user-api-ci

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      KEY: ${{ secrets.KEY }}
      DB_URL: ${{ secrets.DB_URL }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: docker pull mongo:latest
    - run: docker run --name mongo -d  -p 27017:27017 mongo

    - run: npm ci

    - run: npm run lint
    - run: DB_URL=${DB_URL} KEY=${KEY} npm run test

    - run: docker stop mongo
    - run: docker rm mongo
